language: ruby
branches:
  only:
    - master
rvm:
  - 1.9.3
bundler_args: --without development
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test