postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: helpme_<%= Rails.env %>
  min_messages: ERROR

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults