postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: helpme_<%= Rails.env %>
  min_messages: ERROR

defaults: 
  adapter: postgresql
  encoding: unicode
  database: helpme_test
  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults